// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC0mmFwE_253t7knD4kiNy18P6AvROocE',
    appId: '1:581782270698:web:fb3adca18ec507f0af9d93',
    messagingSenderId: '581782270698',
    projectId: 'expense-care-2ef8d',
    authDomain: 'expense-care-2ef8d.firebaseapp.com',
    storageBucket: 'expense-care-2ef8d.firebasestorage.app',
    measurementId: 'G-VBXD5LVY8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPLtdwnRp0l3aGQc5b8UwqQhwKR7-KOc',
    appId: '1:581782270698:android:c232e03ec17d03a9af9d93',
    messagingSenderId: '581782270698',
    projectId: 'expense-care-2ef8d',
    storageBucket: 'expense-care-2ef8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2eU-XkHYRiMGg8-p6emAMhDx3biWBL8s',
    appId: '1:581782270698:ios:08ba0e5ba8e4a502af9d93',
    messagingSenderId: '581782270698',
    projectId: 'expense-care-2ef8d',
    storageBucket: 'expense-care-2ef8d.firebasestorage.app',
    iosClientId: '581782270698-aktq766u6or1s3kjvnnm7te19vmpban6.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC0mmFwE_253t7knD4kiNy18P6AvROocE',
    appId: '1:581782270698:web:b9c810a8d600beb4af9d93',
    messagingSenderId: '581782270698',
    projectId: 'expense-care-2ef8d',
    authDomain: 'expense-care-2ef8d.firebaseapp.com',
    storageBucket: 'expense-care-2ef8d.firebasestorage.app',
    measurementId: 'G-138316VMLX',
  );

}